GET http://localhost:8080/

###

GET http://localhost:8080/usuario

###

GET http://localhost:8080/usuario/d2615a10-5043-4d7c-8a26-918e8de7b6ac

###

POST http://localhost:8080/usuario
Content-type: application/json

{
    "email": "lucio.lemos.385@ufrn.edu.br",
    "senha":"Diferent45@" 
}

###

PUT http://localhost:8080/usuario?id=c371cec8-cf70-429b-8291-a6fb31b14303
Content-type: application/json

{
    "email": "luciolemos.j5@gmail.com",
    "senha":"diferent@1968#" 
}

### 

DELETE http://localhost:8080/usuario?id=d2615a10-5043-4d7c-8a26-918e8de7b6ac
