GET http://localhost:8080/


###

GET http://localhost:8080/listar

###

GET http://localhost:8080/pesquisar/440b1e56-de3a-451c-8172-449704310859

###

POST http://localhost:8080/cadastrar
Content-type: application/json

{
    "nome": "Lúcio",
    "endereco":"Rua Lúcio Viveiros 1112",
    "RG": "1010297644/MD"   
}

###

PUT http://localhost:8080/editar?id=f714e617-5664-4235-ac61-793d6f2cb1b5
Content-type: application/json

{
    "nome": "Lúcio Flávio Lemos",
    "endereco":"Rua Alexandrino de Alencar 1592",
    "RG": "1010297644/MD"
   
}

### 

DELETE http://localhost:8080/excluir?id=61547cbc-71f7-4b8a-a1d4-2267a954433e
