GET http://localhost:8080/


###

GET http://localhost:8080/aluno

###

GET http://localhost:8080/aluno/42ac6171-7c74-47e6-9fa9-c21b35cf9db8

###

POST http://localhost:8080/aluno
Content-type: application/json

{
    "nome": "Lúcio Lemos",
    "endereco":"Rua Lúcia Viveiros nº 1112",
    "RG": "1010297644/MD"   
}

###

PUT http://localhost:8080/aluno?id=c2d8643e-92b3-47e2-a609-418f0352947a
Content-type: application/json

{
    "nome": "Lúcio Flávio Lemos",
    "endereco":"Rua Alexandrino de Alencar 1592",
    "RG": "1010297644/MD"
   
}

### 

DELETE http://localhost:8080/aluno?id=c2d8643e-92b3-47e2-a609-418f0352947a
