GET http://localhost:8080/


###

GET http://localhost:8080/listar

###

GET http://localhost:8080/pesquisar/42ac6171-7c74-47e6-9fa9-c21b35cf9db8

###

POST http://localhost:8080/cadastrar
Content-type: application/json

{
    "nome": "FLDFGDGDFGDGDF",
    "endereco":"Rua Lúcio Viveiros 1112",
    "RG": "1010297644/MD"   
}

###

PUT http://localhost:8080/editar?id=7f563eca-f117-4889-8be2-de468b5811df
Content-type: application/json

{
    "nome": "Lúcio",
    "endereco":"Rua Alexandrino de Alencar 1592",
    "RG": "1010297644/MD"
   
}

### 

DELETE http://localhost:8080/excluir?id=42ac6171-7c74-47e6-9fa9-c21b35cf9db8
